// const myNumber = [1,2,3,4,5,6,7,8,9,10,11,12,13]

// // let sum =myNumber.map((num) =>num-12)
// const NewMu = myNumber.map((num)=>num*12).map((num)=>num +1).filter((num) =>num>10)
// console.log(NewMu)
// reduce Method:

/**
 * An array of integers.
 */
// const arrow = [1, 2, 3, 4, 5, 6, 7];

// const output = arrow.reduce((acc,currVal)=>{
//     return acc + currVal;
// },0)

// console.log(output)

